
spring:
  security:
    oauth2:
      client:
        registration:
          github: # can be any name I want !!
            clientId: Iv1.731596c579d3b990 # github-app-client-id-here
            clientSecret: 1a16900f622b3b74d6d2e1efa40c53a63ad8705d # github-app-client-secret-here
            google:
              clientId: 700086744673-keplb3hc6ere9uiqddg4aleho4i08g37.apps.googleusercontent.com #yr client id
              clientSecret: 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 #yr client secret